apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-mkjtpqdc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-mkjtpqdc:3570701b7beb4e6c693bda8c009709ab3f878d44@sha256:59210e474d5bfd04811766704c91a2ee8b734c48fa59298039999dcff635e8be
          name: container-image
